"""Wire format (v1). Plain JSON over HTTP - nothing here assumes a Python sender.

Timestamps must be RFC 3339 with an explicit offset (e.g. "2026-09-17T10:15:30.123456Z").
Naive timestamps are rejected so clients in any language can't silently send local time.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator, model_validator

from profiler_service.config import MAX_ATTRIBUTES

Category = Literal["general", "cryptographic"]
Phase = Literal["baseline", "remediated"]
ID_PATTERN = r"^[A-Za-z0-9._:\-]{1,64}$"
AttrValue = str | int | float | bool


class RunCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    run_id: str | None = Field(default=None, pattern=ID_PATTERN, description="Optional; generated by the Service if omitted")
    service: str = Field(min_length=1, max_length=128)
    label: str = Field(min_length=1, max_length=256)
    phase: Phase
    metadata: dict[str, Any] = Field(default_factory=dict, description="Free-form environment info (sdk, runtime, host, ...)")


class RunComplete(BaseModel):
    model_config = ConfigDict(extra="forbid")

    completed_at: AwareDatetime | None = None


class RunOut(BaseModel):
    run_id: str
    service: str
    label: str
    phase: Phase
    created_at: str
    completed_at: str | None
    metadata: dict[str, Any]
    span_count: int
    sample_count: int


class SpanIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    run_id: str = Field(pattern=ID_PATTERN)
    service: str = Field(min_length=1, max_length=128)
    category: Category
    span_id: str = Field(pattern=ID_PATTERN, description="Unique within the run; chosen by the sender")
    parent_span_id: str | None = Field(default=None, pattern=ID_PATTERN)
    span_name: str = Field(min_length=1, max_length=256)
    start_time: AwareDatetime
    end_time: AwareDatetime
    duration_ms: float = Field(ge=0, allow_inf_nan=False)
    attributes: dict[str, AttrValue] = Field(default_factory=dict, description="Optional extension, e.g. {\"algorithm\": \"MD5\"}")

    @field_validator("attributes")
    @classmethod
    def _limit_attributes(cls, v: dict) -> dict:
        if len(v) > MAX_ATTRIBUTES:
            raise ValueError(f"at most {MAX_ATTRIBUTES} attributes")
        for key, value in v.items():
            if not 1 <= len(key) <= 64:
                raise ValueError("attribute keys must be 1-64 characters")
            if isinstance(value, str) and len(value) > 256:
                raise ValueError("string attribute values must be <= 256 characters")
        return v

    @model_validator(mode="after")
    def _check(self) -> SpanIn:
        if self.end_time < self.start_time:
            raise ValueError("end_time is before start_time")
        if self.parent_span_id == self.span_id:
            raise ValueError("span cannot be its own parent")
        return self


class SampleIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    run_id: str = Field(pattern=ID_PATTERN)
    service: str = Field(min_length=1, max_length=128)
    category: Category
    metric_name: str = Field(pattern=r"^[a-z][a-z0-9_]{0,63}$", description="e.g. cpu_pct, memory_mb")
    value: float = Field(allow_inf_nan=False)
    unit: str = Field(min_length=1, max_length=32)
    timestamp: AwareDatetime


class IngestResult(BaseModel):
    accepted: int
